// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetRepositoriesData, GetRepositoriesResponses, GetRepositoriesGroupedData, GetRepositoriesGroupedResponses, PostWorkflowsData, PostWorkflowsResponses, PostWorkflowsRunsData, PostWorkflowsRunsResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getRepositories = <ThrowOnError extends boolean = false>(options?: Options<GetRepositoriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetRepositoriesResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/repositories',
        ...options
    });
};

export const getRepositoriesGrouped = <ThrowOnError extends boolean = false>(options?: Options<GetRepositoriesGroupedData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetRepositoriesGroupedResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/repositories/grouped',
        ...options
    });
};

export const postWorkflows = <ThrowOnError extends boolean = false>(options: Options<PostWorkflowsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostWorkflowsResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/workflows',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const postWorkflowsRuns = <ThrowOnError extends boolean = false>(options: Options<PostWorkflowsRunsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostWorkflowsRunsResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/workflows/runs',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};