// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions, useQuery } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { getAdminSessionDebug, getRepositories, getRepositoriesGrouped, getWorkflowsForARepository, type Options, postRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRuns, postWorkflows } from '../sdk.gen';
import type { GetAdminSessionDebugData, GetRepositoriesData, GetRepositoriesGroupedData, GetWorkflowsForARepositoryData, GetWorkflowsForARepositoryResponse, PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsData, PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsResponse, PostWorkflowsData, PostWorkflowsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getAdminSessionDebugQueryKey = (options?: Options<GetAdminSessionDebugData>) => createQueryKey('getAdminSessionDebug', options);

export const getAdminSessionDebugOptions = (options?: Options<GetAdminSessionDebugData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAdminSessionDebug({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAdminSessionDebugQueryKey(options)
    });
};

export const useGetAdminSessionDebugQuery = (options?: Options<GetAdminSessionDebugData>) => {
    return useQuery(getAdminSessionDebugOptions(options));
};

export const getRepositoriesQueryKey = (options?: Options<GetRepositoriesData>) => createQueryKey('getRepositories', options);

export const getRepositoriesOptions = (options?: Options<GetRepositoriesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getRepositories({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRepositoriesQueryKey(options)
    });
};

export const useGetRepositoriesQuery = (options?: Options<GetRepositoriesData>) => {
    return useQuery(getRepositoriesOptions(options));
};

export const getRepositoriesGroupedQueryKey = (options?: Options<GetRepositoriesGroupedData>) => createQueryKey('getRepositoriesGrouped', options);

export const getRepositoriesGroupedOptions = (options?: Options<GetRepositoriesGroupedData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getRepositoriesGrouped({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRepositoriesGroupedQueryKey(options)
    });
};

export const useGetRepositoriesGroupedQuery = (options?: Options<GetRepositoriesGroupedData>) => {
    return useQuery(getRepositoriesGroupedOptions(options));
};

export const postWorkflowsMutation = (options?: Partial<Options<PostWorkflowsData>>): UseMutationOptions<PostWorkflowsResponse, AxiosError<DefaultError>, Options<PostWorkflowsData>> => {
    const mutationOptions: UseMutationOptions<PostWorkflowsResponse, AxiosError<DefaultError>, Options<PostWorkflowsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWorkflows({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWorkflowsForARepositoryMutation = (options?: Partial<Options<GetWorkflowsForARepositoryData>>): UseMutationOptions<GetWorkflowsForARepositoryResponse, AxiosError<DefaultError>, Options<GetWorkflowsForARepositoryData>> => {
    const mutationOptions: UseMutationOptions<GetWorkflowsForARepositoryResponse, AxiosError<DefaultError>, Options<GetWorkflowsForARepositoryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await getWorkflowsForARepository({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsMutation = (options?: Partial<Options<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsData>>): UseMutationOptions<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsResponse, AxiosError<DefaultError>, Options<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsData>> => {
    const mutationOptions: UseMutationOptions<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsResponse, AxiosError<DefaultError>, Options<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRuns({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
