// This file is auto-generated by @hey-api/openapi-ts

import { type Options, getAdminSessionDebug, getRepositories, getRepositoriesGrouped, postWorkflows, getWorkflowsForARepository, postRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRuns } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { GetAdminSessionDebugData, GetRepositoriesData, GetRepositoriesGroupedData, PostWorkflowsData, PostWorkflowsResponse, GetWorkflowsForARepositoryData, GetWorkflowsForARepositoryResponse, PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsData, PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsResponse } from '../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getAdminSessionDebugQueryKey = (options?: Options<GetAdminSessionDebugData>) => createQueryKey('getAdminSessionDebug', options);

export const getAdminSessionDebugOptions = (options?: Options<GetAdminSessionDebugData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAdminSessionDebug({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAdminSessionDebugQueryKey(options)
    });
};

export const getRepositoriesQueryKey = (options?: Options<GetRepositoriesData>) => createQueryKey('getRepositories', options);

export const getRepositoriesOptions = (options?: Options<GetRepositoriesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getRepositories({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRepositoriesQueryKey(options)
    });
};

export const getRepositoriesGroupedQueryKey = (options?: Options<GetRepositoriesGroupedData>) => createQueryKey('getRepositoriesGrouped', options);

export const getRepositoriesGroupedOptions = (options?: Options<GetRepositoriesGroupedData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getRepositoriesGrouped({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRepositoriesGroupedQueryKey(options)
    });
};

export const postWorkflowsQueryKey = (options: Options<PostWorkflowsData>) => createQueryKey('postWorkflows', options);

export const postWorkflowsOptions = (options: Options<PostWorkflowsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postWorkflows({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postWorkflowsQueryKey(options)
    });
};

export const postWorkflowsMutation = (options?: Partial<Options<PostWorkflowsData>>): UseMutationOptions<PostWorkflowsResponse, AxiosError<DefaultError>, Options<PostWorkflowsData>> => {
    const mutationOptions: UseMutationOptions<PostWorkflowsResponse, AxiosError<DefaultError>, Options<PostWorkflowsData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postWorkflows({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWorkflowsForARepositoryQueryKey = (options: Options<GetWorkflowsForARepositoryData>) => createQueryKey('getWorkflowsForARepository', options);

export const getWorkflowsForARepositoryOptions = (options: Options<GetWorkflowsForARepositoryData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getWorkflowsForARepository({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getWorkflowsForARepositoryQueryKey(options)
    });
};

export const getWorkflowsForARepositoryMutation = (options?: Partial<Options<GetWorkflowsForARepositoryData>>): UseMutationOptions<GetWorkflowsForARepositoryResponse, AxiosError<DefaultError>, Options<GetWorkflowsForARepositoryData>> => {
    const mutationOptions: UseMutationOptions<GetWorkflowsForARepositoryResponse, AxiosError<DefaultError>, Options<GetWorkflowsForARepositoryData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await getWorkflowsForARepository({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsQueryKey = (options: Options<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsData>) => createQueryKey('postRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRuns', options);

export const postRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsOptions = (options: Options<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRuns({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsQueryKey(options)
    });
};

export const postRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsMutation = (options?: Partial<Options<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsData>>): UseMutationOptions<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsResponse, AxiosError<DefaultError>, Options<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsData>> => {
    const mutationOptions: UseMutationOptions<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsResponse, AxiosError<DefaultError>, Options<PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRuns({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};